services:
  app:  
    container_name: url-shortener-app
    build:
      context: ..
      dockerfile: docker/Dockerfile

    ports:
      - "6000:9000"

    depends_on:
      sqlserver:
        condition: service_started
      redis:
        condition: service_started
    
    env_file:
      - ../.env
    networks:
      - url_shortener

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: url-shortener-nginx
    ports:
      - "8085:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - url_shortener

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/health"]
      interval: 30s
      timeout: 10s
      retries: 3 

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-url-shortener
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}
    env_file:
      - ../.env 
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'SELECT 1' | /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P $SA_PASSWORD"]
  
  redis:
    image: redis:alpine
    container_name: redis-url-shortener
    ports:
      - "6385:6379"
    volumes:
      - redis_data:/data
    networks:
      - url_shortener
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

networks:
  url_shortener:
    driver: bridge

volumes:
  sqlserver_data:
  redis_data: